apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /export/volumedata/consul2
    server: devboot01
